./mfcobdb2.sh DMLCALLR.cob
./mfcobdb2.sh GSIOSTUB.cob
./mfcobdb2.sh LAGPRTST.cob
./mfcobdb2.sh LCOBOLE3.cob
./mfcobdb2.sh LCOBOLEX.cob
./mfcobdb2.sh LCOPYBEX.cob
./mfcobdb2.sh LHIERCHX.cob
./mfcobdb2.sh LHIERCHY.cob
./mfcobdb2.sh LPOCTDTR.cob
./mfcobdb2.sh LZZCALEN.cob
./mfcobdb2.sh LZZCOPY1.cob
./mfcobdb2.sh LZZCTRD1.cob
./mfcobdb2.sh LZZCTRM1.cob
./mfcobdb2.sh LZZCTRM2.cob
./mfcobdb2.sh LZZCTRM3.cob
./mfcobdb2.sh LZZCTRM4.cob
./mfcobdb2.sh LZZCTRM5.cob
./mfcobdb2.sh LZZENDE2.cob
./mfcobdb2.sh LZZENDEV.cob
./mfcobdb2.sh LZZEX001.cob
./mfcobdb2.sh LZZHEAD.cob
./mfcobdb2.sh LZZHEADP.cob
./mfcobdb2.sh LZZJCLEX.cob
./mfcobdb2.sh LZZJOBE2.cob
./mfcobdb2.sh LZZJOBE3.cob
./mfcobdb2.sh LZZJOBEX.cob
./mfcobdb2.sh LZZLOGEX.cob
./mfcobdb2.sh LZZMERG1.cob
./mfcobdb2.sh LZZPAUSE.cob
./mfcobdb2.sh LZZWRKDY.cob
./mfcobdb2.sh LZZXRF01.cob
./mfcobdb2.sh LZZXRF02.cob
./mfcobdb2.sh PACKLIST.cob
./mfcobdb2.sh RECVYGEN.cob
./mfcobdb2.sh SSXMTSGN.cob
