CREATE TABLE "MFUSER"."CUSTOMERS" 
   (	"CUSTOMERID" NUMBER(*,0), 
	"CUSTOMERNAME" VARCHAR2(255), 
	"CONTACTNAME" VARCHAR2(255), 
	"COUNTRY" VARCHAR2(100), 
	"CITY" VARCHAR2(100), 
	"POSTALCODE" VARCHAR2(20), 
	 PRIMARY KEY ("CUSTOMERID")
  USING INDEX  ENABLE
   ) ;
