CREATE TABLE "MFUSER"."ORDERS" 
   (	"ORDERID" NUMBER(*,0), 
	"CUSTOMERID" NUMBER(*,0), 
	"ORDERDATE" DATE, 
	"PRODUCT" VARCHAR2(255), 
	"QUANTITY" NUMBER(*,0), 
	 PRIMARY KEY ("ORDERID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "MFUSER"."CUSTOMERS" ("CUSTOMERID") ENABLE
   ) ;
